/* Generated By:JJTree: Do not edit this line. ASTImportDeclaration.java */

package fn.parser;

public class ASTImportDeclaration extends FnParseNode {
  public ASTImportDeclaration(int id) {
    super(id);
  }

  public ASTImportDeclaration(FnParser p, int id) {
    super(p, id);
  }

}
