/* Generated By:JJTree: Do not edit this line. ASTOut.java */
package fn.parser;

public class ASTName extends FnParseNode {

    public ASTName(int id) {
        super(id);
    }

    public ASTName(FnParser p, int id) {
        super(p, id);
    }

    public String getType() {
        return firstToken.next.image;
    }
}
