/* Generated By:JJTree&JavaCC: Do not edit this line. FnParserConstants.java */
package fn.parser;

public interface FnParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int ABSTRACT = 13;
  int ASSERT = 14;
  int BOOLEAN = 15;
  int BREAK = 16;
  int BYTE = 17;
  int CASE = 18;
  int CATCH = 19;
  int CHAR = 20;
  int CLASS = 21;
  int CONST = 22;
  int CONTINUE = 23;
  int _DEFAULT = 24;
  int DO = 25;
  int DOUBLE = 26;
  int ELSE = 27;
  int ENUM = 28;
  int EXTENDS = 29;
  int FALSE = 30;
  int FINAL = 31;
  int FINALLY = 32;
  int FLOAT = 33;
  int FOR = 34;
  int GOTO = 35;
  int IF = 36;
  int IMPLEMENTS = 37;
  int IMPORT = 38;
  int INSTANCEOF = 39;
  int INT = 40;
  int INTERFACE = 41;
  int LONG = 42;
  int NATIVE = 43;
  int NEW = 44;
  int NULL = 45;
  int PACKAGE = 46;
  int PRIVATE = 47;
  int PROTECTED = 48;
  int PUBLIC = 49;
  int RETURN = 50;
  int SHORT = 51;
  int STATIC = 52;
  int STRICTFP = 53;
  int SUPER = 54;
  int SWITCH = 55;
  int SYNCHRONIZED = 56;
  int THIS = 57;
  int THROW = 58;
  int THROWS = 59;
  int TRANSIENT = 60;
  int TRUE = 61;
  int TRY = 62;
  int VOID = 63;
  int VOLATILE = 64;
  int WHILE = 65;
  int FN = 66;
  int GROUP = 67;
  int TYPE = 68;
  int IN = 69;
  int OUT = 70;
  int EVAL = 71;
  int EXEC = 72;
  int INIT = 73;
  int PARAMETER = 74;
  int SETUP = 75;
  int META = 76;
  int SLIN = 77;
  int EXIN = 78;
  int CVAR = 79;
  int INTEGER_LITERAL = 80;
  int DECIMAL_LITERAL = 81;
  int HEX_LITERAL = 82;
  int OCTAL_LITERAL = 83;
  int FLOATING_POINT_LITERAL = 84;
  int EXPONENT = 85;
  int CHARACTER_LITERAL = 86;
  int STRING_LITERAL = 87;
  int IDENTIFIER = 88;
  int LETTER = 89;
  int DIGIT = 90;
  int LPAREN = 91;
  int RPAREN = 92;
  int LBRACE = 93;
  int RBRACE = 94;
  int LBRACKET = 95;
  int RBRACKET = 96;
  int SEMICOLON = 97;
  int COMMA = 98;
  int DOT = 99;
  int AT = 100;
  int ASSIGN = 101;
  int LT = 102;
  int BANG = 103;
  int TILDE = 104;
  int HOOK = 105;
  int COLON = 106;
  int EQ = 107;
  int LE = 108;
  int GE = 109;
  int NE = 110;
  int SC_OR = 111;
  int SC_AND = 112;
  int INCR = 113;
  int DECR = 114;
  int PLUS = 115;
  int MINUS = 116;
  int STAR = 117;
  int SLASH = 118;
  int BIT_AND = 119;
  int BIT_OR = 120;
  int XOR = 121;
  int REM = 122;
  int LSHIFT = 123;
  int PLUSASSIGN = 124;
  int MINUSASSIGN = 125;
  int STARASSIGN = 126;
  int SLASHASSIGN = 127;
  int ANDASSIGN = 128;
  int ORASSIGN = 129;
  int XORASSIGN = 130;
  int REMASSIGN = 131;
  int LSHIFTASSIGN = 132;
  int RSIGNEDSHIFTASSIGN = 133;
  int RUNSIGNEDSHIFTASSIGN = 134;
  int ELLIPSIS = 135;
  int RUNSIGNEDSHIFT = 136;
  int RSIGNEDSHIFT = 137;
  int GT = 138;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"fn\"",
    "\"group\"",
    "\"type\"",
    "\"in\"",
    "\"fout\"",
    "\"eval\"",
    "\"exec\"",
    "\"init\"",
    "\"parameter\"",
    "\"setup\"",
    "\"meta\"",
    "\"slin\"",
    "\"exin\"",
    "\"cvar\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
  };

}
