/* Generated By:JJTree: Do not edit this line. ASTFnExpression.java */
package fn;

public class ASTFnExpression extends FnParseNode {

    public ASTFnExpression(int id) {
        super(id);
    }

    public ASTFnExpression(FnParser p, int id) {
        super(p, id);
    }
}
