/* Generated By:JJTree: Do not edit this line. ASTFnBlock.java */
package fn;

public class ASTFnBlock extends FnParseNode {

    public ASTFnBlock(int id) {
        super(id);
    }

    public ASTFnBlock(FnParser p, int id) {
        super(p, id);
    }
}
