/* Generated By:JJTree: Do not edit this line. ASTFnType.java */
package fn;

public class ASTFnType extends SimpleNode {

    public ASTFnType(int id) {
        super(id);
    }

    public ASTFnType(FnParser p, int id) {
        super(p, id);
    }
}
