/* Generated By:JJTree: Do not edit this line. ASTLocal.java */
package fn;

public class ASTLocal extends FnParseNode {

    public ASTLocal(int id) {
        super(id);
    }

    public ASTLocal(FnParser p, int id) {
        super(p, id);
    }
}
