/* Generated By:JJTree: Do not edit this line. ASTOut.java */
package fn;

public class ASTOut extends FnParseNode {

    public ASTOut(int id) {
        super(id);
    }

    public ASTOut(FnParser p, int id) {
        super(p, id);
    }

    public String getType() {
        return firstToken.next.image;
    }
}
