/* Generated By:JJTree: Do not edit this line. C:/Projects/Genetic/PainterRoot/Fn/src/fn\FnParserTreeConstants.java */

package fn;

public interface FnParserTreeConstants
{
  public int JJTFNTOPLEVEL = 0;
  public int JJTFNDEFINITION = 1;
  public int JJTVOID = 2;
  public int JJTIN = 3;
  public int JJTNBIN = 4;
  public int JJTOUT = 5;
  public int JJTFNBLOCK = 6;
  public int JJTLOCAL = 7;
  public int JJTMETA = 8;
  public int JJTFNEXPRESSION = 9;
  public int JJTFNTYPE = 10;
  public int JJTIMPORTDECLARATION = 11;


  public String[] jjtNodeName = {
    "FnTopLevel",
    "FnDefinition",
    "void",
    "In",
    "NBIn",
    "Out",
    "FnBlock",
    "Local",
    "Meta",
    "FnExpression",
    "FnType",
    "ImportDeclaration",
  };
}
