/* Generated By:JJTree: Do not edit this line. ASTFnBlock.java */
package fn.parser;

public class ASTBlock extends FnParseNode {

    public ASTBlock(int id) {
        super(id);
    }

    public ASTBlock(FnParser p, int id) {
        super(p, id);
    }
}
