/* Generated By:JJTree: Do not edit this line. ASTExpression.java */

package fn.parser;

public class ASTExpression extends SimpleNode {
  public ASTExpression(int id) {
    super(id);
  }

  public ASTExpression(FnParser p, int id) {
    super(p, id);
  }

}
