/* Generated By:JJTree: Do not edit this line. ASTLocalDeclaration.java */

package fn.parser;

public class ASTLocalDeclaration extends FnParseNode {
  public ASTLocalDeclaration(int id) {
    super(id);
  }

  public ASTLocalDeclaration(FnParser p, int id) {
    super(p, id);
  }

}
