/* Generated By:JJTree: Do not edit this line. C:\Projects\Genetic\PainterRoot\Fn\src\fn\parser\FnParserTreeConstants.java */
package fn.parser;

public interface FnParserTreeConstants {

    public int JJTFNTOPLEVEL = 0;
    public int JJTFNDEFINITION = 1;
    public int JJTVOID = 2;
    public int JJTLOCALDECLARATION = 3;
    public int JJTBLOCK = 4;
    public int JJTEXPRESSION = 5;
    public int JJTTYPE = 6;
    public int JJTIMPORTDECLARATION = 7;
    public String[] jjtNodeName = {
        "FnTopLevel",
        "FnDefinition",
        "void",
        "LocalDeclaration",
        "Block",
        "Expression",
        "Type",
        "ImportDeclaration"
    ,}
;
}
